### ISSUE TITLE
Toggle menu doesn't work to go back to game

### ISSUE THREAD

**Issue by Pcsl** [libretro/Lakka-LibreELEC#553] opened 2018-10-07 19:20 UTC
I couldn't find if this is a bug or a feature as the popular sentence says but I think it's a weird behavior that after pressing toggle button Lakka/Retroarch menu is not closing.

Version 2.1.1
Device: Raspberry 3 B
Gamepad: Gamesir G3S (Xiaoji)
What I did:
   Launch a game
   Toggle the menu to open Lakka menu
   Press menu again to go back to the game
   It doesn't actually go back to the game
- What did I expect to happen:
Actually going back to the game when I pressed the "Home"/toggle button.
 
Let me know if you need any logs.

**Comment by RobLoach** [comment] 2018-10-07 20:27
Confirmed... May be fixed in 1.7.5, but I have yet to test it.

Related: https://github.com/libretro/RetroArch/issues/6574

**Comment by ToKe79** [comment] 2018-10-08 06:31
From what I observed - pressing the "guide" button on my Logitech F710 brings me to the RetroArch frontend, pressing it again does not return to the emulation. However, when using my Xiaomi Bluetooth controller (no "guide" button, I have this feature mapped to L3+R3), pressing L3+R3 switches between emulation and RetroArch frontend correctly. Same works for F1 on the keyboard, at least from what I remember/observed.

**Comment by Pcsl** [comment] 2018-10-08 06:38
> 
> 
> From what I observed - pressing the "guide" button on my Logitech F710 brings me to the RetroArch frontend, pressing it again does not return to the emulation. However, when using my Xiaomi Bluetooth controller (no "guide" button, I have this feature mapped to L3+R3), pressing L3+R3 switches between emulation and RetroArch frontend correctly. Same works for F1 on the keyboard, at least from what I remember/observed.

I just confirmed this is same for my Gamesir G3S, just the Home/Guide button is the one not working properly to return to the game but pressing Select+Start (as I mapped it to use it) does.

**Comment by RobLoach** [comment] 2018-12-24 23:45
Related? https://github.com/libretro/RetroArch/issues/7756

**Comment by orbea** [comment] 2018-12-25 18:35
This is a duplicate of https://github.com/libretro/RetroArch/issues/5127.

**Closed** 2020-08-18 23:39 UTC
