### ISSUE TITLE
PCSX ReARMed Crashing (Lakka 4.0 Nintendo Switch)

### ISSUE THREAD

**Issue by DrunkenMonk0001** [libretro/Lakka-LibreELEC#1671] opened 2022-03-30 04:44 UTC
**Which version of Lakka are you using?**
  4.0
**What system hardware are you using?**
  Nintendo Switch
**What did you do?**
  Selected game (e.g Digimon World 1), PCSXrearmed core and had bios enabled
**What did you expect to happen?**
  Game being able to reach the menu load a game save.
**What happened instead?**
  Complete freeze on the accessing memory card screen, emulator became completely unresponsive, needed to be closed entirey. Loading an existing save state would load the game partially then hard crash moments later.

Debugging steps I had found to partially resolve the problem:
Disabling real bios allows games to load without crashing, however not using the real bios disables too many other features (e.g consistent sound in games)

Using SCPH5002 with Digimon World 1 (EUR) as my example, It will seemingly work perfect at first, until the emulator freezes when using a bios and attempting to access the save/load menu and without the bios it functions fine, but has almost a complete loss of all sound.

Possibly related to issue #1651

**Comment by ToKe79** [comment] 2022-03-31 22:20
duplicate of #1651

**Closed as completed by ToKe79** 2022-03-31 22:20 UTC
