### ISSUE TITLE
Lakka 2.1 bananaPi booting problem

### ISSUE THREAD

**Issue by isanphone** [libretro/Lakka-LibreELEC#308] opened 2017-12-12 12:08 UTC
`lakka: [failed] Failed to start load Kernel Modules` on display and nothing happened
write on pc and mac as normal img
lakka 2 was write and works great

**Comment by Kivutar** [comment] 2017-12-14 14:08
Duplicate of https://github.com/libretro/Lakka-LibreELEC/issues/307

**Closed by Kivutar** 2017-12-14 14:08 UTC
