### ISSUE TITLE
Flycast issue (RPi4B) Lakka Stable aarch64 3.5.2 using Vulkan driver

### ISSUE THREAD

**Issue by atlus666** [libretro/Lakka-LibreELEC#1541] opened 2021-10-27 13:22 UTC
This issue tracker is NOT for help or support. Please use one of the following channels for help and support:
- the Lakka forum (https://forums.libretro.com/c/libretro/lakka-tv-general)
- via IRC @ #lakkatv on freenode.net
- #lakkatv on libretro discord https://discord.gg/retroarch

Before you report a bug make sure you have tried the latest nightly version of Lakka at https://nightly.builds.lakka.tv/latest/. Your bug might be already fixed.

If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using? 3.5.2
- What system hardware are you using? RPi4B

After update Lakka 3.5.2
Flycast can not load any Dreamcast Game (include cdi & gdi)
It't only show can't load content and exit flycast

**Comment by dmrlawson** [comment] 2021-10-30 20:22
Flycast will hopefully work with vulkan when the v3dv driver with Vulkan 1.1 support is released and we update. It should be soonish: https://www.raspberrypi.com/news/vulkan-update-version-1-1-conformance-for-raspberry-pi-4/

**Comment by gouchi** [comment] 2021-10-31 08:24
According to Khronos, the [conformance application](https://www.khronos.org/conformance/adopters/conformant-products/vulkan#submission_596) has been submitted using Mesa 2.1.3 but it seems it is [not yet integrated](https://gitlab.freedesktop.org/mesa/mesa/-/commits/21.3/src/broadcom/vulkan) as the [commit for enabling Vulkan 1.1](https://gitlab.freedesktop.org/mesa/mesa/-/commit/acb83e1b13d43586bbda0ffb609afbe60da0b8aa) is not in this branch. We may have to wait for next major release Mesa 22.

Some [information about Vulkan 1.1 support](https://mesamatrix.net/#Vulkan1.1) if needed.

**Comment by gouchi** [comment] 2022-03-10 19:27
[Mesa 22.0.0](https://docs.mesa3d.org/relnotes/22.0.0.html) has been released !

**Comment by gouchi** [comment] 2022-03-12 10:44
@atlus666 Can you make a test with [nightly builds](https://nightly.builds.lakka.tv/latest/) to see if the issue is fixed as Mesa 22 has been enabled.

Thank you.

**Comment by gouchi** [comment] 2022-03-12 12:54
Closing this issue as RPi4 users reported it is working now with nightly builds.

**Closed by gouchi** 2022-03-12 12:54 UTC
