### ISSUE TITLE
TP-LINK UB500 Bluetooth adapter dindn't work with PC on Lakka 4.2

### ISSUE THREAD

**Issue by Torrens1** [libretro/Lakka-LibreELEC#1733] opened 2022-08-29 12:17 UTC
I've touched on this topic before [https://github.com/libretro/Lakka-LibreELEC/issues/1567].
Theoretically, the problem was solved with version 4.1 but unfortunately for me it still does not work. I will add that I am not as proficient with linux as I would like and I do not know how I can update the karnel or add the driver manually.

**Comment by Torrens1** [comment] 2022-08-29 12:30
[log-2022-08-29-12.17.02.zip](https://github.com/libretro/Lakka-LibreELEC/files/9444488/log-2022-08-29-12.17.02.zip)

**Comment by Ntemis** [comment] 2022-08-29 12:36
duplicate of https://github.com/libretro/Lakka-LibreELEC/issues/1567

**Closed as completed by Ntemis** 2022-08-29 12:36 UTC
