### ISSUE TITLE
Lakka 2.3.2. RPi1/0/GPi issues

### ISSUE THREAD

**Issue by brightentayle** [libretro/Lakka-LibreELEC#884] opened 2020-01-23 21:58 UTC
The new (supposedly) stable release of Lakka appears to be broken in a few places. I've tested GPi-2.3.2 specifically, and can confirm that lr-gpsp crashes upon trying to start up.

There's also a glitch in User Interface -> Appearance -> Menu Color Theme (seems to happen in RGUI specifically) that doesn't have a name in the menu, appears as Anti-Zenburn on the item list and uses Classic Green's color scheme.

P. S. The new Accessibility feature can also not be hidden for whatever reason, even though it does nothing for Raspberry Pi-based builds, as they don't have any kind of TTS.

**Comment by generalerusso** [comment] 2020-01-23 22:05
Confirming the lr-gpsp crash-to-menu issue, all roms used (around 20) all seem to crash to the main menu after some 15-20 seconds wait.

**Comment by generalerusso** [comment] 2020-01-23 22:37
Another issue regarding lr-fbalpha2012 is when choosing UNIBIOS for the bios for playing NeoGeo roms. In Lakka v2.3.1 it will choose the most updated version in the neogeo.zip (generally 3.0), but in 2.3.2 it seems to load always Unibios 1.2.

**Comment by natinusala** [comment] 2020-01-24 09:00
Can you give me logs of the mgba and gpsp crashes please?

As for that BIOS issue I suppose that is a change in logic in RetroArch, can you reproduce it on desktop?

**Comment by brightentayle** [comment] 2020-01-27 12:19
gpSP in particular gives out this, which makes me think Lakka-RPi.GPICase.arm-2.3.2.img has this core compiled for the wrong architecture.

![this happened](https://user-images.githubusercontent.com/38193034/73174194-71eaa100-4107-11ea-9d44-da208f282dd4.png)

**Comment by IndegoRune** [comment] 2020-04-30 06:19
This is still an issue.

**Comment by gouchi** [comment] 2020-08-16 17:10
Hi,

Do you still reproduce your issue with this [nightly build images](https://nightly.builds.lakka.tv/2020-08-07) ?

Thank you.

**Comment by IndegoRune** [comment] 2020-08-19 12:35
How are you going to close this without any kind of resolution or answer? We have yet to see a new stable Lakka on GPi, and the old one is outdated as heck by this point.

You are asking if an issue is fixed in a nightly, when most of us likely don't mess with nightlies.

**Comment by natinusala** [comment] 2020-08-19 14:31
Nightlies are here to field test bug fixes and new features. I let you wait for the upcoming stable then.

**Comment by Ntemis** [comment] 2020-08-19 15:59
Also i need to add that  2.3.x is end of life so anyway you shouldnt expect any fixes to drop any time soon except the ones you will sent as a pr.

**Comment by Ntemis** [comment] 2020-08-19 16:04
@natinusala lesson learned we should stop merging hit and run pr's since we cant support the device we don't own.

**Comment by brightentayle** [comment] 2020-08-19 16:28
Okay, first of all, I have to say that I didn't get to test the nightlies yet, because I didn't have the time to do so. Second of all...

@Ntemis You do realise the GPi Case is not an emulation handheld of its' own, right? The GPi Lakka is basically the Raspberry Pi 0/1 build but slightly stripped down (yet still including lr-pcsx-rearmed, which doesn't even run at full speed even with frame skipping), with the safe shutdown patch and also the screen drivers included. So, aside from those three factors, all those issues me and a few others have described there would easily apply to the Pi 0/1 build of 2.3.2, because the thing **houses** a Raspberry Pi 0. If that makes any sense.

**Comment by Ntemis** [comment] 2020-08-19 16:40
I know what a GPi Case is but still changes nothing as i dont own any Pi 0/1 to test and make sure core is fixed.
If anyone else has it and can give it a shot surely be my guest and he/she can reopen this case.
For the time being please try to try the nightly images for the sake of all of us lets leave this release in peace and stop beating a dead horse. ofc feel free to fork and fix anything you like but before that again please try the latest nightly and if needed open a new issue so we can fix it this time

**Comment by wfce** [comment] 2020-08-19 17:08
If 2.3.2 is end-of-life and we should not be using it, please update your website saying as much.

**Comment by Ntemis** [comment] 2020-08-19 17:12
2.3.2 is tagged as a stable release that can be used until v3.x comes out, what you need us to say on the website? that you didnt test previous 2.3.x releases and you came on the last stable before transition to a new framework and demand a fix? where were you when releases were pouring hot one after the other? The train has departed so i suggest you move on too. Regards

**Comment by wfce** [comment] 2020-08-19 17:50
Nobody is demanding anything. 

We downloaded the version available on the website and found an issue, so we reported it.

**Comment by Ntemis** [comment] 2020-08-19 23:21
Thank you for your contribution but unfortunately there wont be any new versions released from this branch as it has being decommissioned. 
Your interest in transforming Lakka OS into a better distro is highly appreciated.
All efforts are now moved on for next major release and we continue passionate and focused to deliver the best RetroArch Turn-key Distro OS.
Feel welcome to test and report any issues by testing the new nightly images from here  https://nightly.builds.lakka.tv/

**Comment by brightentayle** [comment] 2020-08-23 19:51
Can confirm, it crashes with the same error on the most recent nightly.

...also, I'd really advise people to stop throwing corporate excuses around and at least buy the platforms they're developing for, because begging people to see if something works really isn't going to make debugging any easier. _Especially_ if those platforms cost five to ten bucks.

**Comment by natinusala** [comment] 2020-08-23 19:54
RPi0 support was brought by an external contributor who's no longer around. There is nobody to maintain it anymore The end result is that we're going to drop support for that board, period.

**Comment by brightentayle** [comment] 2020-08-23 19:58
@natinusala Thanks for clarifying that

**Comment by natinusala** [comment] 2020-08-23 20:02
It might be worth to continue support it if we get hold of a GPICase, but other than that I don't know if the rpi0 is still a relevant board anymore.

**Comment by Ntemis** [comment] 2020-08-23 23:48
Not only that but that core is failing everywhere as i read so is not a lakka issue at all.
Is correctly reported here https://github.com/libretro/gpsp/issues/71
This issue stays closed end of story.

**Comment by Ntemis** [comment] 2020-08-24 00:00
I went ahead and fixed it but you guys should wait for the new nightly to let me know

**Comment by john-parton** [comment] 2020-08-24 01:09
I have the GPi Case, and it's a really lovely piece of hardware. I understand that the Zero is basically ancient at this point, but it's still a versatile little device.

I'm a web developer, so this isn't my usual wheel house, but I can definitely test things out.

I'll try to test that fix tomorrow.

**Comment by SethBarberee** [comment] 2020-08-24 03:30
Compiling from master with recent commit and running on RPi0 just fine with gpSP. Latest nightly should be fine.

**Comment by IndegoRune** [comment] 2020-08-24 03:55
Cool!

**Comment by john-parton** [comment] 2020-08-24 14:22
I'm not seeing the latest nightly.

Don't see it here: http://nightly.builds.lakka.tv/2020-08-24/

The log says this: http://nightly.builds.lakka.tv/2020-08-24/_logs/nightly_2020-08-24.txt

```
Following targets were skipped - could not find existing build folder:
A64.arm
H3.arm
H6.arm
AMLGX.arm
Generic.x86_64
Generic.i386
MiQi.arm
RK3328.arm
RK3399.arm
TinkerBoard.arm
Gamegirl.arm
GPICase.arm
RPi.arm
RPi2.arm
RPi4.arm
```

Not familiar with the build system. Why would this happen?

**Comment by SethBarberee** [comment] 2020-08-24 16:20
@john-parton Probably due to the nightly build cleanout. Sometimes we have to cleanout the nightly build manually. I compiled my working image from commandline.

For RPi0/RPi1:
`DISTRO=Lakka ARCH=arm PROJECT=RPi DEVICE=RPi make image`

For GPiCase:
`DISTRO=Lakka ARCH=arm PROJECT=RPi DEVICE=GPiCase make image`

**Comment by metchebe** [comment] 2020-08-24 17:11
Hi @SethBarberee, just curious, does the fixed gpSP have the dynarec included?

**Comment by SethBarberee** [comment] 2020-08-24 18:32
Hmm looks like it wasn't included since platform was changed to only `unix`

**Comment by Ntemis** [comment] 2020-08-24 22:45
Issue is now reported fixed, so lets close it. Thanks for the reports

**Closed by Ntemis** 2020-08-24 22:45 UTC
