### ISSUE TITLE
Downloads fecked

### ISSUE THREAD

**Issue by xcs011** [libretro/Lakka-LibreELEC#769] opened 2019-09-05 23:02 UTC
Okay sorry for fucking with pull requests.

But yeah, the download mirror appears to be down, and gives me a 404 error for every version.

**Comment by Ntemis** [comment] 2019-09-05 23:50
http://nightly.builds.lakka.tv/

**Comment by natinusala** [comment] 2019-09-06 07:53
The main download server indeed yields a 404 error, I'll see what is the cause this evening

**Comment by natinusala** [comment] 2019-09-10 14:45
Will be fixed with the 2.3 release

**Closed by natinusala** 2019-09-10 14:45 UTC
