### ISSUE TITLE
LAKKA on Pi 4 B 8gb no boot, no start, send error message on booting action

### ISSUE THREAD

**Issue by palitofat** [libretro/Lakka-LibreELEC#1011] opened 2020-08-18 21:56 UTC
If you are sure that it's a bug in Lakka, please answer the following questions:

- Which version of Lakka are you using?
Lasted and previus vers
![IMG_20200818_153645](https://user-images.githubusercontent.com/66711134/90569478-2fec7f80-e16b-11ea-8c32-2e7053a958a7.jpg)
ions is same!
**Lakka-RPi4.arm-3.0-devel-20200817005022-50aca1f.img.gz**

- What system hardware are you **using?**
**Raspberry pi 4 B 8 giga bites**

- What did you do?
Burn on sd card of 32gb class10 with balena

- What did you expect to happen?
I expect run LAKKA OS but no funtion

- What happened instead?
To moment to chance sd for lakka sd. Generate a n error boot secuense.

**Comment by palitofat** [comment] 2020-08-18 21:57
Apreciated help me with this unconvenient please. 
Sorry with my English

**Comment by Ntemis** [comment] 2020-08-18 23:09
you haved to start lakka with lakka sd in and system power off then on, you cant change sd on the fly if i get it right on what you are reporting here "To moment to chance sd for lakka sd. Generate a n error boot sequence."

**Comment by Ntemis** [comment] 2020-08-18 23:14
If you are trying to boot from usb then try an sdcard and report back

**Comment by palitofat** [comment] 2020-08-18 23:30
Obviusly I power off raspberry pi4. Then I extract sd os. And put on the new sd lakka. And power on. Inmediatly put the message cant boot

**Comment by palitofat** [comment] 2020-08-18 23:33
No I not put sd lakka os on port usb 3.5. I put lakka on port sd for os boot. With power off pi4

**Comment by Ntemis** [comment] 2020-08-18 23:53
Is clear now,thanks for the report, it will be investigated asap

**Comment by palitofat** [comment] 2020-08-19 00:03
one more thing, once the sd is burned with lakka. I cannot visualize what is inside the sd. I cant see the boot files, config, kernel, etc.
I think the lakka operating system for pi 4 8gigas is corrupt.

**Comment by palitofat** [comment] 2020-08-20 12:58
Good morning, any solution o no yet

**Comment by Ntemis** [comment] 2020-08-20 13:22
I will link you to the latest rpi4 image to test 
https://nightly.builds.lakka.tv/2020-08-20/RPi4.arm/Lakka-RPi4.arm-3.0-devel-20200820023653-59d5c4b.img.gz
Let me know if the issue is fixed, thanks

**Comment by palitofat** [comment] 2020-08-20 15:30
Hello Ntemis
nothing yet.
I tried to burn it with balena etcher and it gave error during the burning process. after I finish this, turn off the rasp, exchange cards and the same problem. I send you photos of the processes. Thank you
![IMG_20200820_092158](https://user-images.githubusercontent.com/66711134/90792416-abfbda00-e2c7-11ea-973e-5fec2d3bacce.jpg)
![IMG_20200820_092248](https://user-images.githubusercontent.com/66711134/90792432-b1592480-e2c7-11ea-8d9a-b74a0fa3e454.jpg)
![IMG_20200820_092356](https://user-images.githubusercontent.com/66711134/90792446-b5854200-e2c7-11ea-9f54-c3e3f9c8347d.jpg)

**Comment by Ntemis** [comment] 2020-08-20 16:11
Please write the image again with out extracting it and make sure balena etcher verified the burn.

**Comment by palitofat** [comment] 2020-08-20 17:03
![IMG_20200820_105750](https://user-images.githubusercontent.com/66711134/90802487-90e39700-e2d4-11ea-9493-2634c8a2e6d6.jpg)
![IMG_20200820_105915](https://user-images.githubusercontent.com/66711134/90802494-94771e00-e2d4-11ea-8da1-32445b70cdf2.jpg)
![IMG_20200820_105916](https://user-images.githubusercontent.com/66711134/90802501-97720e80-e2d4-11ea-915d-f5fca4db6446.jpg)

Balena configured with your instrucctions 
No expulse
Validate processes activated

Hello again.
Same situation
No correct burn
Look the pictures

![IMG_20200820_105529](https://user-images.githubusercontent.com/66711134/90802475-8d501000-e2d4-11ea-8038-9dabb9178177.jpg)

**Comment by palitofat** [comment] 2020-08-20 17:13
Remember my raspberry is 4b and 8 gb of memory ram. I dont nowk if that is a problem. I bougth recently on amazon. 
Maybe bios
Maybe Lakka files
I dont nowk

**Comment by palitofat** [comment] 2020-08-20 21:04
Hello any avance?

**Comment by Ntemis** [comment] 2020-08-20 21:36
The issue is on your part there is nothing wrong with lakka image https://imgur.com/ZzZklYx

**Comment by palitofat** [comment] 2020-08-20 21:55
Ahhh ok

**Closed** 2020-08-20 22:40 UTC
