### ISSUE TITLE
Hangs after second boot banana pi/ pro

### ISSUE THREAD

**Issue by pcs3rd** [libretro/Lakka-LibreELEC#317] opened 2017-12-19 22:10 UTC
(banana pro) first boot works fine, but afterwards, the pro gets stuck at either starting wpa supplicant  or reached target retroarch

**Comment by aPollO2k** [comment] 2018-01-31 14:57
Can confirm this on PBI M1. I will end in one of this two messages each boot.

**Comment by ToKe79** [comment] 2018-01-31 15:26
probably related to #307

**Comment by vision-4** [comment] 2018-01-31 20:03
got exactly same problem : my bpi m1 stuck in second boot on `[ OK ] Reached target Retroarch.` or `[ OK ] Started WPA supplicant.` or `[ OK ] Started Udevil mount service.`

**Comment by livanh** [comment] 2018-04-06 19:32
Same here. No error message like in #307, it just waits forever

**Comment by CaptainStouf** [comment] 2018-04-09 22:56
Same here using Banana Pi A20. It is stuck on `[ OK ] Reached target Retroarch` after first reboot.

**Comment by Ioalevia** [comment] 2019-09-29 16:54
banana pi a20. tried all latest versions of images. tried nightly versions. two varians: stucks with kernel fail or has ethernet fail. one year ago i used lakka on my device and it worked perfect. if anybody has lakka image for banana pi from 2016-2017????

**Comment by Ntemis** [comment] 2019-09-29 17:08
A20 is EOL and no one i know is working on it.
@natinusala decide to keep ot close this down, your call.

**Comment by natinusala** [comment] 2019-09-30 08:02
As long as the platform is listed on the website we should continue to support it or drop it entirely.

**Comment by Ioalevia** [comment] 2019-09-30 09:30
Ntemis. You don't know me. But i use a20 for 4 years. And i think i'm not alone. lakka was the only variant for a20 to create working retrogaming console. Other OS work not so... ideal.... or don't work at all...
Also natinusala is right. banana pi is listed on the webside. And it is exectly banana pi a20. if it is not more supported- please- show it. or make the same as raspberry. There are a lot of banana models, but only a20 is on the website.
but nobody answer the first question- does anybody have lakka image for banana pi from 2016-2017????

**Comment by natinusala** [comment] 2019-09-30 09:33
No, nobody has it sadly

**Comment by Ioalevia** [comment] 2019-09-30 09:43
Even developers? So stop fooling people and delete banana from the list. I can't believe that nobody has  archive of old images. And why developers create latest and nightly versions? For other models? But there only one on the website.

**Comment by natinusala** [comment] 2019-09-30 09:45
Human error happened and we lost all the old images, and due to the very volatile nature of libretro we can't rebuild them.

However you can help us diagnose the issue and fix it if you want

**Comment by Ioalevia** [comment] 2019-09-30 10:09
Issues #317, 307, 308, 504, 475, 510, 382, 232, 360, 543

In my case - #308 failed to start load kernel modules
Stuck on [ok] reached target retroarch.

Is it enough? Sorry but it is all i can write with my child on my knees.

**Comment by natinusala** [comment] 2019-09-30 10:11
I was more thinking like getting the crash log and send it to me so that I build a fixed image that you can then try

Seeing as nobody in the team owns a Banana Pi anymore this is the only way to go if you want a fix in a reasonable amount of time

**Comment by Ioalevia** [comment] 2019-09-30 10:40
So give me an instruction please of how i can get the crash log. Banana tries to install image. Resizes storage. Reboots. Ànd stucks.

**Comment by Ntemis** [comment] 2019-09-30 10:57
@kivutar afaik has an a20. Maybe he can send it over to @natinusala so we can start supporting it back

**Comment by natinusala** [comment] 2019-09-30 10:59
Can you:

- add `ssh` to the kernel command line (unsure on how to go on the Banana Pi bootloader)
- connect your board to ethernet
- find the IP address of the board somehow
- connect to SSH using PuTTY
- do `systemctl stop retroarch` then `retroarch -v`
- give me the output of that

**Comment by Ioalevia** [comment] 2019-09-30 11:58
It is a perfect instruction for linux user.... But i think it is impossible for me in windows... So the only variant is to talk to kivutar... Or kill banana....

**Comment by Ioalevia** [comment] 2019-09-30 12:00
Oh. i've forgot. There are one more human error... On the website.... Form lakka.tv/contact/ does not work. No sending letter...

**Comment by natinusala** [comment] 2019-09-30 12:01
What? PuTTY is a Windows program

**Comment by Ioalevia** [comment] 2019-09-30 12:07
Add ssh

**Comment by natinusala** [comment] 2019-09-30 12:08
You need to add SSH to the Banana Pi kernel command line

**Comment by Ioalevia** [comment] 2019-09-30 12:08
How?

**Comment by Ioalevia** [comment] 2019-09-30 12:09
Sorry but it is difficult for me to understand some things....

**Comment by natinusala** [comment] 2019-09-30 12:09
I don't know I'm unfamiliar with the Banana Pi bootloader, Google will have
the answer

**Comment by Ioalevia** [comment] 2019-09-30 12:11
Ok. I'l try to do this. Thanks.

**Comment by ToKe79** [comment] 2019-09-30 13:11
According to https://www.lakka.tv/doc/the-bootloader/, you should edit a file named `uEnv.txt`. This file should be placed on the `LAKKA` partition of your SD card / USB thumb drive. Open this file in your beloved text editor (be it Notepad on Windows) and there should be a line containing the text `boot=...` and other stuff - place the cursor at the end of that line, add a space and `ssh`, save, exit. If not sure, just copy/paste the content of that file as a new comment and one of us will help you. Then put the SD/USB back into your Banana Pi A20 and power on. Make sure Ethernet cable is plugged into the device and the other end of the cable is connected to your router. When the boot process gets to the `Reached target retroarch`, ssh service should be running and you can use [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) to connect to the device.

But first you need to find the IP address of the device. This can be little tricky, but your router should list all of your devices connected to it including the IPv4 address (number dot number dot number dot number).

Start PuTTY, as `Connection type` select `SSH` (should be pre-selected) and in `Host Name (or IP address)` field key in the IP address, or you can bet on your luck and just key in `lakka` (if your router acts also as DNS relay, it just might resolve that host name to an IP address). `Port` should be `22`, if not, change it to `22`. You can also select `Never` in the lower part - `Close window on exit`. Click the `Open` button.

When you get a login prompt `login as:`, key in `root` (you should see as your are typing) and bash the Enter key. Then it will prompt for `Password:`, again, key in `root` (but this time you will not see what you are typing, even no asterisks and the cursor will not move - so don't panic, that's correct) and bash the Enter key again. If all went OK, you should see a shell prompt, soomething like `Lakka:~#` and a cursor.

So now getting the logs. First stop the currently running RetroArch service. Key in
```
systemctl stop retroarch
```
and, yes, bash the Enter key! And now manually start RetroArch in verbose mode, key in
```
retroarch -v
```
and, again, bash the Enter key. It will print bunch of letters and digits. To copy them, just select them with your mouse cursor (do not right click, only select, they will be copied into the "clipboard" automatically) and then paste here as a new comment.

Godspeed!

**Comment by ToKe79** [comment] 2019-09-30 13:20
After reading https://www.lakka.tv/doc/the-bootloader/ thoroughly I found out, that A20 stands also for the CubieBoard2 and CubieTruck?
Doesn't matter, but the line you are probably looking for in `uEnv.txt` (or `.cb2` or `.ct`) is something like:
```
extraargs='console=ttyS0,115200 console=tty0 boot=/dev/mmcblk0p1 disk=/dev/mmcblk0p2 rootwait quiet ssh loglevel=2 hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x1024p60 consoleblank=0'
```
Here the `ssh` is already included, so maybe it is already done also for Banana Pi / all Allwinner A20 variants. So you just need to find the IP address and connect.

**Comment by ToKe79** [comment] 2019-09-30 13:28
One more note: if `ssh` is not in that `extraargs` line, add it within the single quotes and separate from other command with space.

**Comment by Ioalevia** [comment] 2019-10-01 13:05
Thank you for instructions. I'll try it as fast as it possible

**Comment by Ioalevia** [comment] 2019-10-01 15:47
i found lakka in my network. but bootload line... is quite different...
bootargs=console=ttyS0,115200 console=tty0 boot=/dev/mmcblk0p1 disk=/dev/mmcblk0p2 consoleblank=0 quiet
bootcmd=load mmc 0:1 0x43000000 sun7i-a20-bananapi.dtb; load mmc 0:1 0x42000000 KERNEL; bootz 0x42000000 - 0x43000000

**Comment by Ioalevia** [comment] 2019-10-01 15:48
ssh should stay after quiet?

**Comment by Ioalevia** [comment] 2019-10-01 15:54
!!!!!!!!!

login as: root
root@192.168.100.3's password:
###########################################
# Lakka - The DIY retro emulation console #
# ...... visit http://www.lakka.tv ...... #
###########################################

Lakka (official): 2.3.1 (Allwinner.Bananapi.arm)
Lakka:~ # systemctl stop retroarch
Lakka:~ # retroarch -v
[INFO] RetroArch 1.7.8 (Git ea7e682253)
[INFO] === Build =======================================
[INFO] Capabilities: NEON VFPv3 VFPv4
[INFO] Built: Sep 16 2019
[INFO] Version: 1.7.8
[INFO] Git: ea7e682253
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[ERROR] [KMS]: Couldn't find a suitable DRM device.
[INFO] [GL]: Found GL context: null
[INFO] [GL]: Detecting screen resolution 320x240.
[INFO] [GL]: Vendor: (null), Renderer: (null).
[INFO] [GL]: Version: (null).
Segmentation fault (core dumped)
Lakka:~ #

**Comment by ToKe79** [comment] 2019-10-01 18:58
So this looks like missing GLES issue to me. According to above statement (https://github.com/libretro/Lakka-LibreELEC/issues/317#issuecomment-379919188), the last working was 2.1-RC5, which means it was before the merge of the Allwinner devices. At that time `sunxi-mali` was used as `OPENGLES`:

https://github.com/libretro/Lakka-LibreELEC/blob/72314011e80e901ecbe6e75aac6546d8d16ecee8/projects/Bananapi/options#L93-L94

**Comment by Ioalevia** [comment] 2019-10-01 19:27
Can it help build a fixed image?

**Comment by ToKe79** [comment] 2019-10-01 21:37
probably, but not sure...
meanwhile you could test out image based on LibreELEC 9.2 beta: http://nightly.builds.lakka.tv/Lakka-LE9.2/latest/H3.arm/Lakka-H3.arm-2.9-devel-20190917204415-de642b3-bananapi.img.gz

**Comment by Ioalevia** [comment] 2019-10-02 05:07
First error.
Could no initialize ghy ethernet@1c50000
Retrieving file: /extlinux/pxelinux.cfg/degault
ethernet@1c50000 waiting for phy auto negotiation to complete..... Timeout!

When connect ethernet cable
Dhcp client bound to adress 192.168.100.3
***Error: `serverip' not set
Cannot autoload with tftpget
Missing environment variable: pxeuuid
Retrieving file: /extlinux/pxelinux.cfg/c0a86403
Retrieving file: /extlinux/pxelinux.cfg/c0a8640
Retrieving file: /extlinux/pxelinux.cfg/c0a864
Retrieving file: /extlinux/pxelinux.cfg/c0a86
Retrieving file: /extlinux/pxelinux.cfg/c0a8
Retrieving file: /extlinux/pxelinux.cfg/c0a
Retrieving file: /extlinux/pxelinux.cfg/c0
Retrieving file: /extlinux/pxelinux.cfg/c
Retrieving file: /extlinux/pxelinux.cfg/default-arm-sunxi
Retrieving file: /extlinux/pxelinux.cfg/default-arm
Retrieving file: /extlinux/pxelinux.cfg/default

**Comment by Ioalevia** [comment] 2019-10-02 05:13
No flower logo.

**Comment by Ioalevia** [comment] 2019-10-09 07:45
Lakka (official): devel-20191005004050-r28345-g286a2a41f7
no ethernet error more. the same error as Lakka (official): 2.3.1

**Comment by davidKooreman** [comment] 2019-10-09 15:29
I can test if needed with a Bananapi M1+ A20 chipset...

**Comment by davidKooreman** [comment] 2019-10-09 15:30
same results as loalevia here with Lakka-H3.arm-2.9-devel-20190917204415-de642b3-bananapi.img.gz image

**Comment by Ioalevia** [comment] 2019-10-12 16:18
Lakka (official): devel-20191007003917-r28346-g55d917fdd1 (Allwinner.Bananapi.arm)
Lakka:~ # systemctl stop retroarch
Lakka:~ # retroarch -v
[INFO] RetroArch 1.7.8 (Git ea7e682253)
[INFO] === Build =======================================
[INFO] Capabilities: NEON VFPv3 VFPv4
[INFO] Built: Oct  7 2019
[INFO] Version: 1.7.8
[INFO] Git: ea7e682253
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[ERROR] [KMS]: Couldn't find a suitable DRM device.
[INFO] [GL]: Found GL context: null
[INFO] [GL]: Detecting screen resolution 320x240.
[INFO] [GL]: Vendor: (null), Renderer: (null).
[INFO] [GL]: Version: (null).
Segmentation fault (core dumped)

**Comment by Ioalevia** [comment] 2019-10-12 16:19
BUT! HDMI does not work. banana shows flower logo only with component out.

**Comment by Ioalevia** [comment] 2019-10-12 16:26
Lakka-Allwinner.Bananapi.arm-nightly-2019-10-08
the same problem
lakka 2.3.1 works with hdmi but the same problem as earlier.

**Comment by Ioalevia** [comment] 2019-10-12 16:40
Lakka-Allwinner.Bananapi.arm-nightly-2019-10-12
no hdmi connection
no PuTTY connection

**Comment by Ioalevia** [comment] 2019-11-05 06:59
2019-11-04
Image does not work.
Maybe this can help you...
https://www.google.com/url?sa=t&source=web&rct=j&url=http://forum.lemaker.org/thread-3082-1-1.html&ved=2ahUKEwjwj5you9LlAhXODewKHYoODWcQFjAAegQICBAB&usg=AOvVaw3p8EDpgNf1WamYWd6bzMO8&cshid=1572936057258
This image of lakka works on bananapi. But it is old and have mistakes

**Comment by murakas** [comment] 2019-12-21 16:14
@ToKe79 
Hi, I also own a banana pi. I can also participate in testing.

**Comment by Ntemis** [comment] 2019-12-21 17:02
Banana Pi is a A20 soc @ToKe79 has mistaken it for H3 :)
We dont have any A20 boards though so is up to @natinusala & @kivutar

**Comment by khaa-dv** [comment] 2020-01-11 06:09
I also have A20 Banana, I can also participate in testing and providing logs. I also want a working Lakka

**Comment by khaa-dv** [comment] 2020-01-13 09:09
@ToKe79 , @kivutar , I am ready to compile the image for the Banana M1 (A20). Tell me how to do this?

**Comment by kamokar** [comment] 2020-01-15 15:28
Hello. 
I can participate in testing the image as well.

**Comment by WizzardSK** [comment] 2020-02-29 18:55
I still had the working version 2.2.1rc5 on my SD card in BPI, so here you are, it is just the first partition, you also have to create another FAT32 partition called LAKKA_DISK. https://drive.google.com/open?id=1c1zy7xjEycS6V3M1V4G3i0t2p7F1_iKd

**Comment by Ioalevia** [comment] 2020-03-01 15:07
Any instructions of creating FAT32 partition called LAKKA_DISK??

**Comment by WizzardSK** [comment] 2020-03-01 16:23
Yes, I just used KDE Partition Manager or GParted in Linux. Created new partition, set FAT32 (maybe ext4 would work too) and apply.

**Comment by Ioalevia** [comment] 2020-03-01 16:46
so. i use image writer and write image on card. than i create fat32 partition with name LAKKA_DISK. Right?

**Comment by WizzardSK** [comment] 2020-03-01 17:18
Almost, but you first need to create an empty 512MB (fat) partition on sd card and write that image to this partition, cause it is just an partition image, not whole drive. The second step is correct. Hope it will work.

**Comment by Ioalevia** [comment] 2020-03-01 17:31
not so easy but it works. but is it normal- White screen with folders from up to down?

**Comment by Ioalevia** [comment] 2020-03-01 17:32
in my variant there no theme...

**Comment by WizzardSK** [comment] 2020-03-01 18:27
It have it with blue xmb theme. Maybe I should make an image of whole sd card

**Comment by Ioalevia** [comment] 2020-03-01 19:00
yes/ on the ext4 partition on my card there a lot of config folders/ it can not work good without them

**Comment by Ioalevia** [comment] 2020-03-01 19:00
i copied them from 2014 image but it works not so cool///

**Comment by WizzardSK** [comment] 2020-03-03 20:03
I tried to copy whole SD card, but it would create a 32 GB file. So I just coped the data partition, try this: https://drive.google.com/open?id=11PaeV3xi4enetB0Rt7d5SfFTMR95ccHb

**Comment by Ioalevia** [comment] 2020-03-03 21:08
please/ also make copy of your card/ i have 32 card/ maybe it will be the best variant for us/ and thank you very much for help with lakka!!!!

**Comment by WizzardSK** [comment] 2020-03-03 21:56
I can, maybe tomorrow, but please try this data image, it should work. There is my Atari 2600 collection from my childhood console. It is just 512 MB FAT16 resized partition, mostly empty.

**Comment by Ioalevia** [comment] 2020-03-04 04:19
thank you/ i'l try it in a few hours

**Comment by Ioalevia** [comment] 2020-03-04 08:54
so i can create two partitions on sd card. but i can't give leters both of them. so i can't write config files to second partition. maybe i do something wrong(
i try to write 2014 lakka ones more. then i edit partitions. then turn banana on and it install 2014 lakka. then i write your core files to fat16 partition. and at last it works. i connect lakka to lan and see the second partition on my pc. i copy roms and playlists, and they work. but i can't copy 4-5 config folders.

**Comment by WizzardSK** [comment] 2020-03-06 13:12
Ok, I uploaded my full SD card image here https://drive.google.com/open?id=1ww2TID0VAloBjagWuPgvr6JxZ_TlU_Qc so try this, maybe it is better to resize that image before. Now I just have a problem enabling composite out on this image. It is working on the latest Lakka, but it does not fully boot :)

**Comment by Ioalevia** [comment] 2020-03-06 20:45
It's alive!!!! Thank you!!!

**Comment by WizzardSK** [comment] 2020-03-06 20:49
Nice to hear that! I already solved the composite out, now just have to enable analog audio :)

**Comment by khaa-dv** [comment] 2020-03-07 13:35
@Ioalevia , tell me how to write this image so that it works on BPi, please?

**Comment by Ioalevia** [comment] 2020-03-07 14:23
The img size is more than sd card size. Y used win32 disk imager. Before writing he shows the window, where this problem explained. And you agree with it. I think he cut sectors free from data.

**Comment by Ioalevia** [comment] 2020-03-07 19:45
@WizzardSK i tried to connect component out. Screen changed resolution but there no image. Can you tell how did you solve this problem, please? 

Also, did you try this?
"Switching audio device from the GUI
In recent versions of Lakka, you can go to the Audio Settings and switch the Audio Device using the left and right keys. You need to restart RetroArch for this change to take effect."

**Comment by WizzardSK** [comment] 2020-03-07 20:00
Yes, I followed this wiki: https://linux-sunxi.org/Display#TV.2FCVBS

Changed the fex file from sd card,  but first I had to convert script.bin to script.fex using bin2fex utility from Linux and then to convert it back to bin using fex2bin command. Both commands are provided by sunxi-tools in Ubuntu.

I tried to change the audio device, but it seems that Lakka expects that I write the device name, I cannot choose it, cause when I move the arrows, I see no device name. This it the last problem I have with this Lakka installation. 

Also, I had the problem that Atari 2600 games (how do you like them?) were running fastter than I expected. I think that I solved it by disabling "Threaded video" option in Settings - Video menu.

**Comment by Ioalevia** [comment] 2020-03-08 10:07
I tried left right on audio device. It works. Now i have not hdmi but analog audio.

**Comment by WizzardSK** [comment] 2020-03-08 12:21
Interesting, cause left and right buttons did nothing, I had to type that device manually.

**Comment by Ioalevia** [comment] 2020-03-08 12:39
More interesting that it is you image) i did nothing with files. When i ise joystick and turn left there 3 audio devices. Null sanxi and hdmi

**Comment by Ioalevia** [comment] 2020-03-08 13:28
fail. i made fex file. and changed mode frome 0 to 2. but i can't make bin file now

C:\Bin2Fex>fex2bin script.fex script.bin
E: script.fex:16: invalid character at 16.

**Comment by Ioalevia** [comment] 2020-03-08 14:17
[disp_init]
disp_init_enable = 1
disp_mode = 2
screen0_output_type = 3
screen0_output_mode = 4
screen1_output_type = 2
screen1_output_mode = 14
fb0_framebuffer_num = 2
fb0_format = 10
fb0_pixel_sequence = 0
fb0_scaler_mode_enable = 1
fb1_framebuffer_num = 2
fb1_format = 10
fb1_pixel_sequence = 0
fb1_scaler_mode_enable = 1
lcd0_backlight = 197
lcd1_backlight = 197
lcd0_bright = 50
lcd0_contrast = 50
lcd0_saturation = 57
lcd0_hue = 50
lcd1_bright = 50
lcd1_contrast = 50
lcd1_saturation = 57
lcd1_hue = 50

i edited it so. no image. Schould i edit something else?

**Comment by WizzardSK** [comment] 2020-03-09 19:56
Maybe try this, that is my script.bin and script.fex

[script.zip](https://github.com/libretro/Lakka-LibreELEC/files/4308650/script.zip)

**Comment by Ioalevia** [comment] 2020-03-09 20:12
Thank you! I'l try it tomorrow.

**Comment by Ioalevia** [comment] 2020-03-11 08:11
script works. so it is script for hdmi/ and script for composite/ there was a variant for double screen but something is wrong- only hdmi works (double) or both video outputs do not work (clone)/

**Comment by WizzardSK** [comment] 2020-03-11 08:19
I am not sure if I understand. This script works on my BPI and outputs only to composite in PAL format to my TV. I may try to grab whole SD card again and to shrink it.

**Comment by Ioalevia** [comment] 2020-03-11 08:27
Your script works with composite good) and old script works with hdmi good. Two scripts. One of outputs. The idea was to make both outputs work at the same time.

**Comment by WizzardSK** [comment] 2020-03-11 09:12
Ok, understand. I did not even try dual output, cause analog out is enough for me, so you just have to try and combine the config option.

**Comment by WizzardSK** [comment] 2020-03-21 19:11
I found out that some games do not run well. In Yars Revenge I cannot move left and Worms War I runs just monochrome. Maybe it is caused by outdated stella core.

**Comment by sedatbjk** [comment] 2020-06-26 08:41
I'm having the same problem. I have an old version (2.1 rc5) with 16gb sd card. But i have 2 more Banana Pi's with 2gb sd cards. I tried resizing secondary partition and clone it to other 2gb cards, they became un-bootable. If only there's 2.1 rc5 image to download. I have no idea what to try next.

**Comment by bernhard263** [comment] 2020-06-27 17:18
I resized and recompressed the working Lakka 2.1 image from WizzardSK to make it smaller. Before it was 1.5 GB download, 30 GB extracted. Now it's just 300 MB download, 1 GB extracted. Contents are the same, just partitions resized. You can download it here: https://drive.google.com/drive/folders/1asjOuq_cEyWTUz5TcYrZ0g0QdaQZsZ4u?usp=sharing
You can directly write the .xz file to SD card using [Balena Etcher](https://www.balena.io/etcher/).
If you want analog TV out instead of HDMI, download the script.bin from this folder and copy it to the first SD card partition (boot), replacing the original script.bin.

**Comment by bernhard263** [comment] 2020-06-29 13:07
I was also able to get RetroPie running on my Banana Pi (Allwinner A20). There are no images for it, but you can install Armbian with Kernel 3.4 and compile Retropie yourself. Write a message if you need details. I know this hasn't got anything to do with Lakka, but the Lakka images don't work anymore and this is the only way I have found to install a newer version of Retroarch on the Banana Pi.

**Comment by WizzardSK** [comment] 2020-06-29 13:50
How do you enable opengl?

**Comment by sedatbjk** [comment] 2020-06-29 14:07
Armbian with kernel 3.4 from legacy versions section, right ? Is it stable enough to run RetroPie smoothly ? I just want to set up my old crt tv to play atari2600 / nes games.

**Comment by bernhard263** [comment] 2020-06-29 14:22
I have no time to describe the whole process now because it's a lot of small things, but here is what I basically did:
- Download and flash https://dl.armbian.com/_old/bananapi/archive/Armbian_5.90_Bananapi_Ubuntu_xenial_default_3.4.113_desktop.7z (important, it's the only image with old working 3.4 kernel, there is no other one)
- Do not update the kernel, leave it as it is
- Disable desktop in armbian-config (Retropie runs in framebuffer and does not allow desktop)
- Follow sunxi wiki: https://linux-sunxi.org/Mali_binary_driver
Install Mali binary driver:  (section: Installing the Mali userspace driver), MALI_EGL_TYPE must be set to framebuffer, not X11
Test framebuffer driver (section: Verifying the EGL/GLES driver stack)
- Download and install Retropie-Setup https://github.com/RetroPie/RetroPie-Setup
Now the last step is a bit complicated because there are a few build errors, I will show how to fix them when I have more time.

**Comment by bernhard263** [comment] 2020-06-29 16:22
WizzardSK: The driver doesn't support OpenGL, you probably mean OpenGL ES. You can enable support by installing the Mali binary driver as shown on https://linux-sunxi.org/Mali_binary_driver , specifically the file libMali.so, this is the driver that enables OpenGL ES support.
sedatbjk: Performance is very smooth, I have only tried Game Boy and Genesis so far though. It's the same performance as Lakka from what I can tell.

**Comment by WizzardSK** [comment] 2020-06-30 07:37
Yes, OpenGL ES. I see, so only that legacy kernel supports that Mali library?

**Comment by bernhard263** [comment] 2020-06-30 10:02
It's a very complicated problem. The first problem was that the Mali OpenGL ES drivers are proprietary, ARM does not release source code for it. You have to get these drivers from the Chip manufacturer (Allwinner/sunxi), and they never released an updated version that works with new kernels. Then, some years later, Allwinner released an updated driver that also supports newer kernels (see https://bootlin.com/blog/mali-opengl-support-on-allwinner-platforms-with-mainline-linux/ ). The drivers work, but then another problem appeared - as far as I understand, the newer kernels have a bug that prevents the framebuffer device on A20 devices from working. Framebuffer is a very fast method to draw graphics on screen, used by Lakka and Retropie. So you have a working graphics driver, but it can't draw any graphics to the screen. This bug has not been fixed until today, so the new drivers are useless and we have to keep using the legacy kernel 3.4.

**Comment by WizzardSK** [comment] 2020-07-07 14:50
@bernhard263 would you mind sharing that compiled working image, at least the system partition, to some google drive? I am sure it would help a lof of people. I tried to compile those GL ES drivers, but unsuccessfully.

**Comment by bernhard263** [comment] 2020-07-07 14:58
@WizzardSK yes, absolutely! Sorry for leting you wait, I promised to share it and I will upload it in the next few days.

I was still hoping to get it working with one of the newer kernels, and I tried a lot of ideas this week, but no success so far. Then I tried to at least compile the newer r6p2 driver for the old kernel (old kernel version is r3p0), but also no success - it's very hard because the new driver uses lots of code from the newer kernels, and you need to rewrite it to use the old kernel code.

**Comment by bernhard263** [comment] 2020-07-09 12:04
@WizzardSK have a look here:

https://github.com/bernhard263/Bananapi-Retropie/

This contains easy instructions for downloading and installing the components yourself. Please test it and give feedback! I have not uploaded a full image yet, but I might do that in the following days.

**Comment by WizzardSK** [comment] 2020-07-09 18:16
Thank you very much, the guide is really very good and it goes well until I want to install those Retropie core packages. It ends like this. I tried it more times, even upgraded all the packages but I cannot solve this problem.
![obrázok](https://user-images.githubusercontent.com/42868978/87075549-cf3f5e00-c220-11ea-9bef-63eaecca7958.png)
![obrázok](https://user-images.githubusercontent.com/42868978/87075596-e2522e00-c220-11ea-9df9-e2eef5a2c9de.png)

**Comment by bernhard263** [comment] 2020-07-09 18:58
@WizzardSK oh, I'm sorry to hear it didn't work. I have no idea if this guide is 100% working yet. After looking at the log file, I know why it failed, I had this problem too. It is caused by the old Mali OpenGLES headers that come with the old kernel. No modern programs will compile with them. Can you try the following:

sudo mv /usr/include/GLES /usr/include/.GLES
sudo apt-get install libgles2-mesa-dev

and then try again? You could also try the following:

wget -P /usr/include/GLES https://www.khronos.org/registry/OpenGL/api/GLES/gl.h
wget -P /usr/include/GLES https://www.khronos.org/registry/OpenGL/api/GLES/glext.h
wget -P /usr/include/GLES2 https://www.khronos.org/registry/OpenGL/api/GLES2/gl2.h
wget -P /usr/include/GLES2 https://www.khronos.org/registry/OpenGL/api/GLES2/gl2ext.h

and then try again.

**Comment by WizzardSK** [comment] 2020-07-09 21:12
Yes, it indeed works, Emulationstation works and I can run my Atari 2600 games. What is more important, even Stella runs directly in SDL without need of some Xorg and desktop manager. Now I can play with that and try to compile the latest Stella, maybe also try Recalbox, etc. Good work! Do you think that it should work also on other sunxi PCBs like Orange Pi, etc? I think it should, if we use the same Armbian version. I will sure try it also on my Orange Pi PC when I set all the things on this Banana Pi. Thank you very much!

**Comment by bernhard263** [comment] 2020-07-09 21:32
Awesome, that's great to hear! About the other boards, I'm not sure. The problem is that even if they have the same chipset (Allwinner A20), every board needs platform-specific code that tells the kernel about the board's hardware devices and addresses. This code is located in the kernel. This is why you usually cannot use images that were meant for another board, because the image will not have the correct kernel. So you would need at least an Armbian image with a kernel that is specific to your board (Orange PI). And the kernel must also be an old 3.x kernel, because newer kernels will not work with the mali r3p0 driver. The mali driver should work on every sunxi device as long as your kernel is compatible.

**Comment by WizzardSK** [comment] 2020-07-10 19:04
Today I tried to build it on upgraded system to Ubuntu Focal. After a few tries it built Retroarch and Emulationstation, but did not build SDL2. I found in the log that it miss some stropts.h file in include directory. I copied the one from my Xenial working build from another SD card. Then it needs some bits/xtitypes.h file, which is not even on my xenial SD card. When I build it with stropts.h file empty, it builds, but ES does not run, it has some problem with video. I know I should not upgrade to the latest Ubuntu, but I just wanted to try it. Also, I was not able to build the latest Stella in Xenial, but it builds on Focal.

**Comment by bernhard263** [comment] 2020-07-11 06:58
@WizzardSK you could upload the log file here, maybe it will help to see what went wrong

I have another interesting idea. Remember what I said about the graphics driver not working with newer linux kernels? I remember that during a google search, I came across some websites that mentioned this is bug only happens when there is no HDMI monitor connected. I cannot test it because I don't have an external monitor. Maybe you could test it? Install one of the newer Armbian images (Kernel 4.x and 5.x), then type "ls /dev/fb*" to see if you have a framebuffer device available.

**Comment by WizzardSK** [comment] 2020-07-11 17:11
It is very interesting. I installed all those packages with that file, but all of the packages have the file on different location. I also removed my copied file from xenial. The build failed on the same error. I think I shoud start over, because I have made a lot of steps I dont even remember.

I may try that with HDMI, but I still prefer composite out on my TV, I will see :)

[rps_2020-07-11_165611.log.gz](https://github.com/libretro/Lakka-LibreELEC/files/4907279/rps_2020-07-11_165611.log.gz)

**Comment by bernhard263** [comment] 2020-07-30 07:48
@WizzardSK sorry for not replying, I did not receive a notification this time. That's very interesting to hear that you have the framebuffer device working. This should mean that you can use Retropie on the new kernel. This post explains how to install the mali driver on newer kernels:

https://bootlin.com/blog/mali-opengl-support-on-allwinner-platforms-with-mainline-linux/

Can you please test something else, remove the HDMI cable and only connect the Banana Pi over composite out. If /dev/fb0 disappears after a reboot, it would confirm that there is a bug in the newer kernels. The sun4i_drm driver is responsible for this. When the system boots, it removes the standard framebuffer device and replaces it with its own. But if no HDMI cable is connected, it will not create a new framebuffer device after deleting the old one. Without it, there is no graphics output possible and most applications (such as retroarch) will not run.

To find out what causes this, you would have to debug the kernel driver sun4i-drm. This way you might be able to find the error. I will certainly not be able to fix it because my programming experience is very limited, but you could at least message the kernel developers to make them aware of this bug and maybe they'll fix it. 

Another thing that has failed to work on my Armbian image was audio over HDMI. Can you please test the following command on the new kernel (5.4.45): "aplay -l". It should list two devices, HDMI audio and headphone audio, but on my system the HDMI audio is missing, it only worked on the old kernel.

**Comment by WizzardSK** [comment] 2020-08-04 20:30
Yes, I confirm it is like like you said on BPi with the new kernel 5.4.45. The FB device is only present when I connect HDMI cable and turn on the monitor on that HDMI. It is present until reboot, even when I disconnect that monitor before reboot.
I also tried aplay -l and it really only shows one audio device, with or without HDMI cable plugged in.
Thank you for that guide, I will sure try it!

**Comment by WizzardSK** [comment] 2020-08-18 19:22
By the way, I just found this simple guide to enable Lima GPU driver for Mali GPU: https://forum.armbian.com/topic/14595-enable-lima-on-headless-devices

I tried it just on Orange Pi PC, but it works on Focal, so maybe it will also work on Banana Pi :)

**Closed** 2020-08-18 23:35 UTC
