### ISSUE TITLE
[Solved] Boot loop on old PC (2007 Dell Inspiron 1521) Suspect something with GPU?(It wasn't)

### ISSUE THREAD

**Issue by limeabeen** [libretro/Lakka-LibreELEC#618] opened 2019-03-13 01:37 UTC
Thanks for reading this post. Please correct me if I have posted this in the wrong spot or you need more info.

Tried both 32 and 64 bit generic nightly builds. Both have same error. I tried editing the autostart and config files, but to my surprise when I navigated to them, they didn't exist. I tried to just make my own, but that didn't work in the end.

I was able to boot to the DRAW_USE_LLVM=0 retroarch -v using the live USB.

- Which version of Lakka are you using? 
I believe it is 2.2, but the file I used was Lakka-Generic.x86_64-2.2.img.gz
- What system hardware are you using?
2007 Dell Inspiron 1521, it has an AMD x64 bit CPU (i believe 2 core) with 2GB RAM. it has a 120 GB SSD.
- What did you do?
Installed lakka with the live USB onto SSD.
- What did you expect to happen?
Successful boot of lakka with GUI.
- What happened instead?
Looping of the lakka logo on bootup.

Graphics Card LOGS
![IMG_0030](https://user-images.githubusercontent.com/20540926/54247307-68177980-4506-11e9-92fe-144a0a8cfe52.JPG)

01:05.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] RS690M [Radeon Xpress 1200/1250/1270] [1002:791f]
        Subsystem: Dell RS690M [Radeon Xpress 1200/1250/1270] [1028:01fc]
        Kernel driver in use: radeon
03:00.0 Ethernet controller [0200]: Broadcom Limited BCM4401-B0 100Base-TX [14e4:170c] (rev 02)

Lakka (official): 2.2 (Generic.i386)
Lakka:~ # systemctl stop retroarch.service ; retroarch -v
[INFO] RetroArch 1.7.5 (Git b55ed9e)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3
Built: Dec 22 2018
[INFO] Version: 1.7.5
[INFO] Git: b55ed9e
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[INFO] [DRM]: Found 4 connectors.
[INFO] [DRM]: Connector 0 connected: no
[INFO] [DRM]: Connector 0 has 0 modes.
[INFO] [DRM]: Connector 1 connected: yes
[INFO] [DRM]: Connector 1 has 8 modes.
[INFO] [DRM]: Connector 1 assigned to monitor index: #1.
[INFO] [DRM]: Connector 2 connected: no
[INFO] [DRM]: Connector 2 has 0 modes.
[INFO] [DRM]: Connector 3 connected: no
[INFO] [DRM]: Connector 3 has 0 modes.
[INFO] [DRM]: Mode 0: (1280x800) 1280 x 800, 60 Hz
[INFO] [DRM]: Mode 1: (1280x720) 1280 x 720, 60 Hz
[INFO] [DRM]: Mode 2: (1152x768) 1152 x 768, 60 Hz
[INFO] [DRM]: Mode 3: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 4: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 5: (848x480) 848 x 480, 60 Hz
[INFO] [DRM]: Mode 6: (720x480) 720 x 480, 60 Hz
[INFO] [DRM]: Mode 7: (640x480) 640 x 480, 60 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1280x800.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0xb4513e88.
[INFO] [KMS]: New FB: 1280x800 (stride: 5120).
[INFO] [GL]: Vendor: X.Org R300 Project, Renderer: Gallium 0.4 on ATI RS690.
[INFO] [GL]: Version: 2.1 Mesa 17.1.3.
[INFO] [GL]: Using resolution 1280x800
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ...
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Resetting shader to defaults ...
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Keyboard #0 (/dev/input/event4).
[INFO] [udev]: Mouse #0 (/dev/input/event5).
[INFO] [udev]: Mouse #1 (/dev/input/mouse0).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: null
[INFO] Found shader "/tmp/shaders/bilinear.glslp"
[INFO] Found shader "/tmp/shaders/nearest.glslp"
[INFO] Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] Found shader "/tmp/shaders/stock.glsl"
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 1024 frames
[INFO] ALSA: Buffer size: 2048 frames
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x8417df4
[INFO] [MIDI]: Initializing ...
ALSA lib /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.i386/alsa-lib-1.1.4.1/src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
[ERROR] [MIDI]: snd_seq_open failed with error -2.
[ERROR] [MIDI]: Initialization failed (list of input devices unavailable).
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/storage/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
Unable to find target for this triple (no targets are registered)
Segmentation fault (core dumped)

Thanks again for any help!

**Comment by mlnlbrt** [comment] 2019-03-13 17:52
Looks like a duplicate of the following issues:
https://github.com/libretro/Lakka-LibreELEC/issues/312
https://github.com/libretro/Lakka-LibreELEC/issues/322
https://github.com/libretro/Lakka-LibreELEC/issues/486

Please try `systemctl stop retroarch.service && DRAW_USE_LLVM=0 retroarch`

**Comment by limeabeen** [comment] 2019-03-13 18:41
> Looks like a duplicate of the following issues:
> #312
> #322
> #486
> 
> Please try `systemctl stop retroarch.service && DRAW_USE_LLVM=0 retroarch`

Thanks for the reply!
I have tried this, and I am able to get to lakka (blue screen with white text), but not sure how to apply this knowledge to the SSD, and not sure if i'll have to type this in every time?

@mlnlbrt

**Comment by mlnlbrt** [comment] 2019-03-13 19:59
@limeabeen I would try to do something like this:
- copy `/usr/lib/systemd/system/retroarch.service` to `~/.config/system.d/retroarch-llvm-fix.service`
- edit `~/.config/system.d/retroarch-llvm-fix.service`:
add `Environment=DRAW_USE_LLVM=0` in `[Service]` section OR
modify `Execstart=` in `[Service]` section to contain `DRAW_USE_LLVM=0`

- execute `systemctl disable retroarch`
- execute `systemctl enable retroarch-llvm-fix`

I haven't tried it myself so I am not sure it will work, but this should allow you to disable default `retroarch.service` and execute modified one on each boot.
Probably you will need to experiment with this a little bit.

**Comment by limeabeen** [comment] 2019-03-13 22:36
> @limeabeen I would try to do something like this:
> 
> * copy `/usr/lib/systemd/system/retroarch.service` to `~/.config/system.d/retroarch-llvm-fix.service`
> * edit `~/.config/system.d/retroarch-llvm-fix.service`:
>   add `Environment=DRAW_USE_LLVM=0` in `[Service]` section OR
>   modify `Execstart=` in `[Service]` section to contain `DRAW_USE_LLVM=0`
> * execute `systemctl disable retroarch`
> * execute `systemctl enable retroarch-llvm-fix`
> 
> I haven't tried it myself so I am not sure it will work, but this should allow you to disable default `retroarch.service` and execute modified one on each boot.
> Probably you will need to experiment with this a little bit.

So, I tried what you said, and it worked very well for the USB. I was able to get to lakka and change the fonts and stuff, plus could reboot and let it do its thing (not having to type in commands). However, I still am having issues getting the laptop to boot via the **SSD.** I tried running the installer after doing the above, but still get a constant loop with the lakka fruit logo. Any ideas?
Thanks!! 
![image1](https://user-images.githubusercontent.com/20540926/54319087-70c78880-45b6-11e9-8968-9f5e8a6030fd.jpeg)
![image2](https://user-images.githubusercontent.com/20540926/54319088-70c78880-45b6-11e9-92b6-835831001bf9.jpeg)
![image3](https://user-images.githubusercontent.com/20540926/54319089-71601f00-45b6-11e9-8adb-759c51eaffbd.jpeg)
@mlnlbrt

**Comment by mlnlbrt** [comment] 2019-03-14 15:40
@limeabeen Good to hear it works. :) 

I guess you need to repeat these steps in your SSD install, have you tried?

**Comment by limeabeen** [comment] 2019-03-14 17:02
@mlnlbrt 

The problem I am having there is that those folders/files don't exist when I navigate to them on the SSD.

**Comment by mlnlbrt** [comment] 2019-03-14 18:58
@limeabeen Do you want to use the whole SSD for Lakka?
If so, then I would suggest to "burn" Lakka.img (using `dd`) straight to SSD instead of USB and boot from the SSD. Lakka will resize its partitions at the first boot to fill the whole disk. 

I use Lakka this way, didn't need to use the installer.

**Comment by limeabeen** [comment] 2019-03-14 19:25
@mlnlbrt 
I'm willing to try that. 

Will this make importing ROMs impossible since lakka would take up the entire SSD? I might need a bit more guidance, as I'm not the best with linux. I understand your message as don't burn the USB using something like Etcher. However, I need clarification on the next part. Do you suggest using dd to "burn" (clone?) the files from the working environment of the USB to the SSD?

**Comment by mlnlbrt** [comment] 2019-03-17 12:54
@limeabeen please try to install Lakka on your SSD using the following build:
http://buildserver3.lakka.tv/Lakka-Generic.x86_64-2.2-devel-20190316194356-r28258-gbd97ec6.img.gz

It will fail at the first run, but after ssh-ing to the SSD install and running the following command it should work fine:
`echo DRAW_USE_LLVM=0 > /storage/.cache/services/retroarch.conf`

Please let me know if it works for you.

**Comment by limeabeen** [comment] 2019-03-17 16:57
@mlnlbrt Im on it.

**Comment by limeabeen** [comment] 2019-03-17 20:40
@mlnlbrt Same issue as before with the loop cycle.

**Comment by mlnlbrt** [comment] 2019-03-17 20:50
@limeabeen Did you executed the command I mentioned in my previous comment in the storage partition of your SSD?

You can directly access command line, please take a look at "Direct access" section below:
http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface/

**Comment by limeabeen** [comment] 2019-03-17 20:54
@mlnlbrt I have not executed the command from your previous statement because I cannot access SSH yet. I am reading the direct connection documentation now, however, I am not seeing how to actually get to the command line in order to start typing those commands.

**Comment by mlnlbrt** [comment] 2019-03-17 21:01
@limeabeen This is all about creating `retroarch.conf` file with `DRAW_USE_LLVM=0` inside, in the proper place in storage partition of your SSD Lakka install, so you can try another way: 

boot your laptop from a Live USB linux distro and mount storage partition of your Lakka SSD installation somewhere, then go to `.cache/service` directory and execute `echo DRAW_USE_LLVM=0 > retroarch.conf` there.

**Comment by limeabeen** [comment] 2019-03-17 21:06
@mlnlbrt i am creative a live boot of lubuntu, which I will boot off of. I will mount the SSD to linux lubuntu so that lubuntu can "see" the ssd, then go to .cache/service and run echo DRAW_USE_LLVM=0 > retroarch.conf.

Sound correct?

**Comment by mlnlbrt** [comment] 2019-03-17 21:13
@limeabeen yup, that sounds good. Please note there will be two partition on your SSD Lakka install:
- smaller "system" partition in the beginning of the drive
- "storage" partition filling rest of the drive

You will need to work on the second one

**Comment by limeabeen** [comment] 2019-03-17 21:23
@mlnlbrt lubuntu@lubuntu: /newdrive/.cache/services$ echo DRAW_USE_LLVM=0 > retroarch.conf

Permission Denied.  I tried doing sudo as well. 
(sudo echo DRAW_USE_LLVM=0 > retroarch.conf)
(echo sudo DRAW_USE_LLVM=0 > retroarch.conf)

**Comment by mlnlbrt** [comment] 2019-03-17 21:24
@limeabeen try `sudo su -` first

**Comment by limeabeen** [comment] 2019-03-17 21:26
@mlnlbrt  still permission denied. I am wondering if I mounted the drive correctly as this is the first time i've had to do that...

**Comment by mlnlbrt** [comment] 2019-03-17 21:31
@limeabeen try this way, assuming `/dev/sda2` is storage partition of your SSD Lakka install:
- `sudo su -`
- `cd /tmp && mkdir mountpoint`
- `mount /dev/sda2 /tmp/mountpoint`
- `echo DRAW_USE_LLVM=0 > /tmp/mountpoint/.cache/services/retroarch.conf`

-

**Comment by limeabeen** [comment] 2019-03-17 21:46
@mlnlbrt OK, I think it worked. I do not see any errrors, but no success message either. How do I test?

**Comment by mlnlbrt** [comment] 2019-03-17 22:00
@limeabeen if you want to check if the file was created correctly just check if `cat retroarch.conf` returns `DRAW_USE_LLVM=0`.

If everything was done correctly your Lakka SSD install should work fine now.

**Comment by limeabeen** [comment] 2019-03-17 22:11
@mlnlbrt We did it! It;s booting off SSD, and I am able to restart over and over without any errors. Thank you for all your help! I could not have done it without you!

**Comment by gouchi** [comment] 2019-07-02 17:38
Closing this issue as it is fixed.

**Closed by gouchi** 2019-07-02 17:38 UTC

**Comment by pizdjuk** [comment] 2023-12-05 11:57
Still the problem on Samsung N150, Lakka 4.3
