### ISSUE TITLE
Keyboard not working while entering wifi password RPi3 2.1 RC5

### ISSUE THREAD

**Issue by masid101** [libretro/Lakka-LibreELEC#238] opened 2017-10-08 16:53 UTC
Which version of Lakka are you using? 2.1 RC5 (http://static.kivutar.me/Lakka-RPi2.arm-2.1-rc5.img.gz)
What system hardware are you using? RPi3
What did you do? Try to enter wifi password using keyboard
What did you expect to happen? Letters on the screen
What happened instead? Nothing

Using the virtual keyboard with the controller works!

**Comment by Kivutar** [comment] 2017-10-10 05:22
I confirm this bug

**Comment by masid101** [comment] 2017-11-25 12:12
Still not working with 2.1 stable release! As this is a very annoying and even milestoned bug, I don't really get it to release a stable without this being fixed!

**Comment by GAZ082** [comment] 2017-11-25 19:07
Just installed lakka in my cubox-i4 and can't believe this is happening. Please fix ASAP! If you need some extra info please let me know. Thanks!

**Comment by Kivutar** [comment] 2017-12-10 05:07
> Still not working with 2.1 stable release! As this is a very annoying and even milestoned bug, I don't really get it to release a stable without this being fixed!

I didn't want to block the release for a keyboard bug that affects only arm boards where the vast majority of our users are using joypad only.

This, combined to other factors like the fact that it was convenient for me to release 2.1 before my new job starts. It was either this, either 2.1 would still not be available.

@Ntemis pushed a potential fix for this. I'm going to test it as soon as I can. The 2.1 branch is going to get stability updates.

**Comment by Kivutar** [comment] 2017-12-10 12:56
@Ntemis the change doesn't fix the keyboard issue.

**Comment by Ntemis** [comment] 2017-12-10 19:22
Sad to hear @Kivutar will revert it. Thanks for the test

**Comment by Kivutar** [comment] 2017-12-23 05:09
I think it is due to this line https://github.com/libretro/RetroArch/blob/master/input/drivers/udev_input.c#L75

**Comment by Kivutar** [comment] 2017-12-23 05:31
Ok, this image have a fix, I'd like someone to try it please http://static.kivutar.me/unstable/Lakka-RPi2.arm-2.1-devel-20171222232758-r28013-g9f419ef.img.gz

**Comment by masid101** [comment] 2017-12-23 08:45
Sorry, but this fix have no effect here!

**Comment by Kivutar** [comment] 2017-12-23 08:47
Yeah :( it was not that...

**Comment by masid101** [comment] 2017-12-23 09:21
We already had a version where it was working. It was 2.0 or one of the RCs of 2.1. Can't remember the exact one. Just if this info is of any help ...!

**Comment by masid101** [comment] 2017-12-25 11:49
I did some research. It worked in 2.1 RC4.

**Comment by ToKe79** [comment] 2018-01-25 19:41
HI,
can someone please test this RPi2 build: http://nightly.builds.lakka.tv/RPi2-kbd-fix-WIP/
Thank you!

**Comment by masid101** [comment] 2018-01-25 20:07
Sorry, but no effect here!

**Comment by ToKe79** [comment] 2018-01-26 15:14
Thank you for testing.
If anybody can test this image - unfortunately I have no RPi:
http://nightly.builds.lakka.tv/RPi2-kbd-fix-WIP/02_second-try_RC4+retroarch_from_RC5+other_changes/
It is based on RC4, but updated RetroArch (as in RC5) + other minor changes in libretro packages (mostly updated version due to build failing).
Changes on top of RC4:
https://gist.github.com/ToKe79/56aaf0b99b7efa8195eb1414f4e01544

**Comment by ToKe79** [comment] 2018-01-26 15:30
And also an image with patched retroarch:
http://nightly.builds.lakka.tv/RPi2-kbd-fix-WIP/03_third-try_as_second_try+patched_RA/

Changes on top of RC4:
https://gist.github.com/ToKe79/6f1fe54fada1b234ff74500950fc17de

**Comment by kivutar** [comment] 2018-01-26 16:22
Thanks @ToKe79 
I tried your latest image, it still doesn't work.

**Comment by ToKe79** [comment] 2018-01-26 20:42
So back to square 1 - plain RC4 (with only updated melonds, assets, sameboy to fix building) to confirm that I am at the correct commit, that was working.
http://nightly.builds.lakka.tv/RPi2-kbd-fix-WIP/04_fourth-try_plain_RC4/
Thank you for testing.

**Comment by ToKe79** [comment] 2018-01-30 10:57
I made another test build for RPi2:
http://nightly.builds.lakka.tv/RPi2-kbd-fix-WIP/05_CurrentLakka_RetroArch_882fe09/
This time I only reverted retroarch package to the state as of RC4 and the rest of the image is current Lakka-2.1-dev branch (https://github.com/libretro/Lakka-LibreELEC/commit/07b402ca29ce2c32d5df2ef20803f3aacf595a49). If this works I will try to find specific commit that broke it (https://github.com/libretro/RetroArch/compare/882fe09...28397b3).
Compiled from https://github.com/ToKe79/Lakka-LibreELEC/commit/76198d729f2f189d1e4a22cc570cba5639cdbc94

**Comment by masid101** [comment] 2018-01-30 19:11
This one works here on RPi3.

**Comment by ToKe79** [comment] 2018-01-30 19:23
Thank you, I just confirmed same (works) also on S905. Please, stay tuned.

**Comment by ToKe79** [comment] 2018-01-31 07:06
Issue bisected to these commits: https://github.com/libretro/RetroArch/compare/5efb90d...1911aad

**Closed** 2018-01-31 14:07 UTC
Labels: bug

**Comment by mstroh76** [comment] 2018-02-02 22:48
Lakka-RPi.arm-2.1-devel-r28180-g31ef195 and Pi Zero W:
works

**Comment by Mutuduxf** [comment] 2018-03-03 12:01
Lakka-RPi.arm-2.1.img and Pi Zero W:
still can't input the wifi password

**Comment by ToKe79** [comment] 2018-03-03 12:34
@Mutuduxf please use devel build from http://nightly.builds.lakka.tv

**Comment by Shadow322** [comment] 2018-03-07 11:50
@ToKe79  i dont see a raspi3 build at that link?

**Comment by ToKe79** [comment] 2018-03-07 12:19
Hi @Shadow322 
raspi3 = RPi2.arm
There is no "rpi3 optimized build", as there is no significant performance difference.

**Comment by Shadow322** [comment] 2018-03-07 12:21
oh ok ill stick with the better program called Retropie then thanks

**Comment by starquake** [comment] 2018-03-07 13:09
@Shadow322 If you think it fits your needs better then you should definitely switch. I hope you will be more friendly towards the retropie developers though.
